### ISSUE TITLE
Lighter restriction on glob dep maybe?

### ISSUE THREAD

**Issue by seangenabe** [ahmadnassri/glob-promise#1]
Since this is just a small wrapper over the main `glob` call, I think we should impose a lighter restriction on the `glob` dependency. Maybe at least covering a major version (`"5"`)? Or, maybe even the forbidden star (`"*"`)?

I don't think anybody would expect the very basic API to change in about forever.

**Comment by ahmadnassri** [comment]
this sounds reasonable. `*` might just work here, wanna do a PR and claim all the glory? ;)
