### ISSUE TITLE
Typings are missing in npm package

### ISSUE THREAD

**Issue by marvinhagemeister** [ahmadnassri/glob-promise#34]
They are all here in this repo. It seems like the package published on `npm` is a bit outdated or not in sync with `master`.

**Comment by ahmadnassri** [comment]
is there really a need for typings?

**Comment by Aarilight** [comment]
+1 for typings, think this should be reopened. Not having them means dependents using typescript don't have autocomplete or type checking. You have to research the api to figure out how to use it. It doesn't seem like a big deal but it's a little bit of assistance.

Happy to PR if you'd be willing to have them again.
