### ISSUE TITLE
Drop Babel

### ISSUE THREAD

**Issue by tinovyatkin** [ahmadnassri/glob-promise#44]
Any plans to drop Babel following your `mkdirp` module?

**Comment by ahmadnassri** [comment]
yep, slowly making my way through

**Comment by ahmadnassri** [comment]
well, made the change, but `tap` is now broken, tracking the issue here: https://github.com/tapjs/foreground-child/issues/20

**Comment by ahmadnassri** [comment]
released as [`v3.0.0`](https://github.com/ahmadnassri/glob-promise/releases/tag/v3.0.0)
