### ISSUE TITLE
Consider releasing TypeScript typings

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [ahmadnassri/glob-promise#51]
I would love to use this library in TypeScript code.

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

**Comment by ahmadnassri** [comment]
PRs welcome!

**Comment by aluanhaddad** [comment]
Awesome.

I was about to raise this issue and then I checked closed issues.

@JoshuaKGoldberg are you working on this?

**Comment by JoshuaKGoldberg** [comment]
Go ahead! I haven't gotten around to starting.

**Comment by aluanhaddad** [comment]
@JoshuaKGoldberg yeah, I was wondering the same thing.

I also looked over the closed PRs and noticed that types were added and in #28 but then reverted in #31.
