### ISSUE TITLE
Add helper methods to Glob instance

### ISSUE THREAD

**Issue by vjpr** [ahmadnassri/glob-promise#53]
```js
const glob = new Glob
glob.sync()

await glob()
```

**Comment by ahmadnassri** [comment]
not sure what you mean here?

**Comment by vjpr** [comment]
If you create and instance of Glob, can you use it with promises.

Originally I thought you could attach events if you created an instance of glob, but it seems you can only listen for match, end and error events. So maybe not useful anymore.
